# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Firebook' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firebook
  pod 'Firebase'
  pod ‘Firebase/Auth’

  target 'FirebookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebookUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
